server:
  port: 8088

spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/study_springboot_jsp?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
#    username: root
#    password: root
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/study_springboot_jsp?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
          username: root
          password: root
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/study_springboot_jsp_two?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
          username: root
          password: root

  redis:
    password: ljg123..
    timeout: 15000ms
    cluster:
      max-redirects: 3    # 获取失败最大重试次数
      nodes:
        - 182.61.50.148:6379
        - 101.33.236.90:6379
        - 49.235.206.69:6379
        - 182.61.50.148:6399
        - 101.33.236.90:6399
        - 49.235.206.69:6399
    lettuce:
      pool:
        max-active: 1024  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）

  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: /**/*Mapper.xml
  global-config:
    db-config:
      id-type: assign_id
  type-aliases-package: com.eiit.presystemeiit.bean
  type-enums-package: com.eiit.presystemeiit.enum